THUDM/CogDL

- cogdl/layers/srgcn_module.py
- cogdl/models/nn/srgcn.py
- setup.py
1. add srgcn and more signal modules  for attention / normalization / activation
2. modify setup.py
> add srgcn & modify setup.py

- cogdl/datasets/gcc_data.py
- cogdl/tasks/similarity_search.py
- match.yml
- tests/tasks/test_similarity_search.py
Add similarity search
change 2 files：cogdl/datasets/gcc_data.py and match.yml
add 1 file:  cogdl/tasks/similarity_search.py
> Add similarity search

- cogdl/data/sampler.py
- cogdl/datasets/gcc_data.py
- cogdl/models/emb/deepwalk.py
- cogdl/models/emb/prone.py
- cogdl/models/nn/pyg_gcn.py
- cogdl/tasks/attributed_graph_clustering.py
- cogdl/tasks/node_classification.py
- cogdl/tasks/similarity_search.py
- cogdl/trainers/sampled_trainer.py
- match.yml
- tests/tasks/test_attributed_graph_clustering.py
- tests/tasks/test_similarity_search.py
also:
add comments about samplers
add embedding based attributed clustering methods and evaluators
> add sampler support for gpu

- README.md
- cogdl/models/nn/ppnp.py
- examples/gnn_models/ppnp.py
- match.yml
- tests/tasks/test_node_classification.py
Hi,
I've implemented the[ Predict then Propagate: Graph Neural Networks meet Personalized PageRank](https://arxiv.org/pdf/1810.05997.pdf) model in CogDL.
A note, the model basically has 2 modes, which depends or not on a PowerIteration step. They are ppnp and appnp. It's the same base, so they are switched in the `--propagation` flag.
I've also only added _appnp_ to the table as in the paper it shows that it's better than _ppnp_.
> Implemented PPNP model

- cogdl/tasks/__init__.py
- cogdl/tasks/attributed_graph_clustering.py
- cogdl/tasks/base_task.py
- cogdl/tasks/graph_classification.py
- cogdl/tasks/heterogeneous_node_classification.py
- cogdl/tasks/link_prediction.py
- cogdl/tasks/multiplex_link_prediction.py
- cogdl/tasks/multiplex_node_classification.py
- cogdl/tasks/node_classification.py
- cogdl/tasks/node_classification_sampling.py
- cogdl/tasks/pretrain.py
- cogdl/tasks/similarity_search.py
- cogdl/tasks/unsupervised_graph_classification.py
- cogdl/tasks/unsupervised_node_classification.py
Cleaning imports and adding a few typehints in tasks module
> [Quality] Small cleanup in tasks module

- Dockerfile
- README.md
Hi, I created a docker container when developing a model and decided to share it here. let me know if you run into any problems when running it.
> Created docker container for easy installation of the repo

- cogdl/models/nn/sgc.py
- examples/gnn_models/sgc.py
- match.yml
- tests/tasks/test_node_classification.py
Implementation of [Simplifying Graph Convolutional Networks](https://arxiv.org/abs/1902.07153)
> Add SGC model

- cogdl/models/emb/deepwalk.py
- tests/models/emb/test_deepwalk.py
I believe that current testing is insufficient and it would be very easy to introduce bugs that would go undetected. This PR intends to introduce (simple) unit testing of deepwalk model.
This idea of testing can be abstracted and applied to other models as well.
> Unit testing deepwalk

- cogdl/data/data.py
- cogdl/models/nn/graph_unet.py
- cogdl/models/nn/pyg_unet.py
- cogdl/tasks/node_classification.py
- match.yml
- tests/tasks/test_node_classification.py
1. Add graph u-net for node classification
> Add graph unet

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/documentation.md
- .github/ISSUE_TEMPLATE/feature-request.md
- .github/ISSUE_TEMPLATE/installation.md
- .github/ISSUE_TEMPLATE/question-help.md
- .github/PULL_REQUEST_TEMPLATE.md
- README.md
- README_CN.md
- cogdl/options.py
- cogdl/utils.py
- docs/source/index.rst
- docs/source/install.rst
- docs/source/quickstart.rst
- examples/quick_start.py
- tests/test_options.py
- tests/test_utils.py
> [Feature] Add quickstart usage & docs

- docs/source/conf.py
Fix auto-build of `Read the Docs`: import the __version__ properly
> [Bugfix] Fix building docs

- docs/source/conf.py
Fix doc version (from import to read)
> [Bugfix] Fix doc version

- .travis.yml
- docs/requirements.txt
- docs/source/conf.py
Fix dgl-related docs: set default PyTorch backend for DGL
> [Bugfix] Fix dgl-related docs

- docs/requirements.txt
- docs/source/conf.py
- docs/source/data.rst
- docs/source/datasets.rst
- docs/source/layers.rst
- docs/source/models.rst
- docs/source/options.rst
- docs/source/tasks.rst
- docs/source/utils.rst
Fix path of API docs: add cogdl prefix
> [Bugfix] Fix path of api docs

- README.md
- README_CN.md
- cogdl/models/__init__.py
- cogdl/tasks/README.md
update README: move leaderboards to cogdl/tasks/README.md
> [Doc] Update README

- README.md
- README_CN.md
> [Release] New v0.2.0 release

- docs/requirements.txt
Fix readthedocs build: add some dependencies
> [Doc] Fix rtd docs

- .gitignore
- MANIFEST.in
- cogdl/__init__.py
- cogdl/models/agc/pyg_daegc.py
- setup.py
Add the `match.yml` file to the pypi package
> [Bugfix] Fix match.yml

- cogdl/configs.py
- cogdl/match.yml
- cogdl/models/emb/hope.py
- cogdl/models/emb/netsmf.py
- cogdl/models/emb/spectral.py
- cogdl/options.py
- cogdl/tasks/unsupervised_node_classification.py
- setup.py
- tests/tasks/test_unsupervised_node_classification.py
- set liblinear solver for Logistic Regression
- set training percents as input arguments
> [Feature] Update unsupervised node classification setting

- cogdl/tasks/README.md
> update test results in knowledge graph completion

- README.md
- README_CN.md
- cogdl/tasks/README.md
- docs/source/index.rst
- docs/source/install.rst
- Update installation (remove pyg and dgl)
- Update results of unsupervised node classification
> [Doc] Update README & docs

- cogdl/oag/bert_model.py
- cogdl/oag/dual_position_bert_model.py
- cogdl/oag/oagbert.py
- cogdl/oag/oagbert_metainfo.py
- cogdl/oag/utils.py
- examples/oagbert_metainfo.py
- tests/test_oag.py
Add OAGBERT v2: pre-trained model with meta-info.
> [Model] Add oagbert metainfo version

- cogdl/oag/README.md
> [Doc] Add OAGBERT README file

- cogdl/configs.py
- cogdl/models/emb/netsmf.py
- Fix path sampling of netsmf model
- Update best configs of netsmf model
> [Bugfix] Fix netsmf model

- README.md
- README_CN.md
- Add bibtex in README(-CN)
- Add FAQ
> [Doc] Update bibtex

- cogdl/models/nn/grand.py
- cogdl/tasks/node_classification.py
- cogdl/utils/utils.py
1. Fix the bug in calling fast_spmm
> [FixBug] Modify fast-spmm

- README.md
- README_CN.md
- cogdl/__init__.py
- cogdl/experiments.py
- cogdl/options.py
- cogdl/utils/utils.py
- docs/source/api/datasets.rst
- docs/source/api/models.rst
- docs/source/api/tasks.rst
- docs/source/index.rst
- docs/source/quickstart.rst
- Add fast-spmm usage
- Update docs
> [Doc] v0.2.1 release

- README.md
- README_CN.md
- docs/source/index.rst
- Update docs for v0.3.0 release
> [Doc] v0.3.0 release

- MANIFEST.in
- cogdl/__init__.py
- cogdl/layers/spmm_layer.py
- Add spmm files in the manifest file
> [Bugfix] Fix spmm path

- cogdl/layers/spmm_layer.py
- cogdl/operators/computeUtil.h
- cogdl/operators/sddmm.cpp
- cogdl/operators/sddmm_kernel.cu
- cogdl/operators/spmm_kernel.cu
> fix backward of spmm with value

- .travis.yml
- cogdl/data/data.py
- cogdl/data/dataset.py
- cogdl/data/sampler.py
- cogdl/datasets/kg_data.py
- cogdl/datasets/strategies_data.py
- cogdl/datasets/tu_data.py
- cogdl/layers/strategies_layers.py
- cogdl/models/nn/gdc_gcn.py
- cogdl/models/nn/han.py
- cogdl/models/nn/pyg_gtn.py
- cogdl/models/nn/stpgnn.py
- cogdl/trainers/sampled_trainer.py
- cogdl/utils/utils.py
- scripts/installation/gcc.sh
- tests/tasks/test_heterogeneous_node_classification.py
- tests/tasks/test_link_prediction.py
- tests/tasks/test_node_classification.py
- tests/tasks/test_pretrain.py
> [BugFix] Fix bugs in stpgnn and heterogenous training

- cogdl/operators/operators.py
- cogdl/operators/spmm/spmm.cpp
- docs/requirements.txt
- setup.py
> [Bugfix] Fix spmm/sddmm bugs

- cogdl/oag/oagbert.py
- cogdl/oag/oagbert_metainfo.py
- cogdl/oag/utils.py
- docs/requirements.txt
- examples/oagbert/oagbert_metainfo_zh.py
> [Model] Add chinese oagbert

- cogdl/options.py
- cogdl/tasks/base_task.py
- cogdl/tasks/node_classification.py
- cogdl/tasks/unsupervised_node_classification.py
- tests/tasks/test_pretrain.py
- tests/tasks/test_unsupervised_node_classification.py
> [Feature] Save trained model and support inference only in node classification

- cogdl/operators/operators.py
- cogdl/operators/spmm/spmm.cpp
- cogdl/operators/spmm/spmm_kernel.cu
- cogdl/utils/utils.py
- docs/requirements.txt
- setup.py
> optimize fast spmm

- cogdl/operators/sample.py
- cogdl/operators/spmm.py
- cogdl/utils/utils.py
> [Bugfix] Fix exception message

- cogdl/data/data.py
> [BugFix] Fix a bug in subgraph

- cogdl/data/data.py
- cogdl/data/sampler.py
- cogdl/datasets/__init__.py
- cogdl/datasets/customized_data.py
- cogdl/datasets/gatne.py
- cogdl/datasets/gcc_data.py
- cogdl/datasets/gtn_data.py
- cogdl/datasets/han_data.py
- cogdl/datasets/kg_data.py
- cogdl/datasets/matlab_matrix.py
- cogdl/datasets/ogb.py
- cogdl/datasets/planetoid_data.py
- cogdl/datasets/saint_data.py
- cogdl/datasets/strategies_data.py
- cogdl/datasets/tu_data.py
- cogdl/utils/evaluator.py
- cogdl/utils/utils.py
- docs/source/introduction.rst
- tests/datasets/test_data.py
1. Fix bugs in Graph
2. Support loading dataset through `build_dataset_from_path`
> [Data] Fix bugs in Graph and Dataset

- cogdl/oag/README.md
- cogdl/oag/oagbert_metainfo.py
- examples/oagbert/oagbert_encode_paper.py
- tests/tasks/test_encode_paper.py
> [WIP] New Interface for Encoding Paper

- README.md
- README_CN.md
- cogdl/__init__.py
- cogdl/operators/mhspmm.py
> [Doc] v0.4 release

- cogdl/utils/utils.py
- examples/custom_dataset.py
> [BUGS] Fix bugs in using Graph and fast-spmm

- cogdl/data/data.py
- cogdl/utils/utils.py
-  [x] All changes have test coverage
> [BugFix] Fix bugs in graph.edge_weight

- cogdl/pipelines.py
- cogdl/utils/utils.py
- examples/generate_emb.py
- tests/test_pipelines.py
> [Feature] Add emb pipeline

- cogdl/data/dataset.py
- cogdl/datasets/__init__.py
- cogdl/datasets/customized_data.py
- cogdl/utils/utils.py
- docs/source/index.rst
- docs/source/task/supervised_graph_classification.rst
- docs/source/task/unsupervised_graph_classification.rst
- docs/source/tutorial/custom_dataset.rst
- docs/source/tutorial/custom_gnn.rst
- docs/source/tutorial/graph.rst
- docs/source/tutorial/index.rst
- docs/source/tutorial/node_classification.rst
- examples/custom_dataset.py
1. Add a brief tutorial for CogDL
2. Modify customized dataset
> [Doc] Add a brief tutotial in docs

- cogdl/options.py
- cogdl/tasks/__init__.py
> [Feature] Refine task import

- cogdl/datasets/rec_data.py
- cogdl/match.yml
- cogdl/pipelines.py
- cogdl/tasks/recommendation.py
- examples/recommendation.py
- tests/test_pipelines.py
> [Pipeline] Recommendation pipeline

- cogdl/layers/__init__.py
- cogdl/layers/base_layer.py
- cogdl/layers/gine_layer.py
- tests/test_layers.py
> [Feature] Add message passing layers

- cogdl/operators/mhspmm.py
- cogdl/operators/spmm.py
- cogdl/operators/spmm/mhTranspose.cu
- cogdl/operators/spmm/spmm_kernel.cu
> fix bugs in calling cusparse API

- cogdl/data/data.py
- cogdl/data/dataset.py
- cogdl/data/sampler.py
- cogdl/datasets/ogb.py
- cogdl/datasets/planetoid_data.py
- cogdl/layers/deepergcn_layer.py
- cogdl/match.yml
- cogdl/models/base_model.py
- cogdl/models/nn/deepergcn.py
- cogdl/models/nn/gcn.py
- cogdl/models/nn/revgcn.py
- cogdl/tasks/node_classification.py
- cogdl/trainers/sampled_trainer.py
1. Add dataset `ogbn-proteins`
2.. support `deepergcn` and `revgen` with edge_features
Due to the limitation of GPU memory , you may run the following command, which uses `random_cluster`  not only in training but also in evaluation.
``python scritps/train.py --dataset ogbn-proteins --model revgen --task node_classification --trainer random_cluster --val-n-clusteer 5``
> [Feature] Support ogbn-proteins with edge_feature

- cogdl/layers/actgcnii_layer.py
- cogdl/layers/actmlp_layer.py
- cogdl/layers/actsage_layer.py
- cogdl/layers/sage_layer.py
- cogdl/models/nn/gcnii.py
- cogdl/models/nn/graphsage.py
- cogdl/operators/actnn.py
- cogdl/operators/actnn/actnn.cc
- cogdl/operators/actnn/actnn.cu
- cogdl/utils/utils.py
- tests/models/ssl/test_generative_models.py
- tests/tasks/test_link_prediction.py
- tests/tasks/test_node_classification.py
> [Layer] Add more act layers

- README.md
- README_CN.md
- cogdl/__init__.py
- docs/source/index.rst
> [Doc] v0.4.1

- cogdl/data/dataloader.py
- cogdl/data/sampler.py
- cogdl/datasets/ogb.py
- cogdl/datasets/planetoid_data.py
- cogdl/datasets/saint_data.py
- cogdl/runner/controller/data_controller.py
- cogdl/runner/options.py
- cogdl/runner/runner.py
- cogdl/runner/runner_utils.py
- cogdl/trainers/distributed_sampled_trainer.py
- cogdl/utils/evaluator.py
- cogdl/wrappers/data_wrapper/base_data_wrapper.py
- cogdl/wrappers/data_wrapper/node_classification/cluster_dw.py
- cogdl/wrappers/model_wrapper/base_model_wrapper.py
- cogdl/wrappers/model_wrapper/node_classification/node_classification_mw.py
- scripts/main.py
> [Update] Add customized early-stopping 

- README.md
- README_CN.md
- paperlist/README.md
> [Paperlist] 100 GNN papers

- .gitmodules
- third_party/README.md
> [Submodule] Add FastMoE as third-party library

- cogdl/datasets/README.md
> [DATASET] Add description for datasets

- README.md
- README_CN.md
- cogdl/__init__.py
- cogdl/data/data.py
- cogdl/datasets/gtn_data.py
- cogdl/experiments.py
- cogdl/layers/gat_layer.py
- cogdl/models/__init__.py
- cogdl/operators/edge_softmax.py
- cogdl/operators/sample.py
- cogdl/utils/spmm_utils.py
- examples/simple_hgn/README.md
- examples/simple_hgn/conv.py
- examples/simple_hgn/run.py
- tests/tasks/test_node_classification.py
- Update the spmm utils (especially mhspmm)
- Fix simple_hgn example
> [Utility] Update spmm utils

- MANIFEST.in
- cogdl/__init__.py
- cogdl/operators/spmm.py
> [Bugfix] Fix packing operator files

- README.md
- README_CN.md
- cogdl/__init__.py
- docs/source/index.rst
> [Doc] Prepare v0.5.2 release

- cogdl/datasets/geom_data.py
- cogdl/datasets/rd2cd_data.py
- docs/source/tutorial/node_classification.rst
> [Dataset] Update rd2cd datasets

- cogdl/data/dataset.py
- cogdl/experiments.py
- cogdl/operators/spmm/spmm.cpp
- cogdl/operators/spmm/spmm_kernel.cu
- cogdl/options.py
- cogdl/trainer/trainer.py
- cogdl/utils/spmm_utils.py
> [Feature] Support fp16

- cogdl/experiments.py
- Don't copy args in the last variant
> [Bugfix] Fix copying args

- docs/requirements.txt
- setup.py
> [Dependency] Fix numpy version

- .travis.yml
- cogdl/datasets/kg_data.py
- cogdl/datasets/matlab_matrix.py
- cogdl/datasets/saint_data.py
- cogdl/oag/oagbert.py
- Update download links of Tsinghua Cloud
> [Dataset] Update download links

- cogdl/layers/jittor/__init__.py
- cogdl/layers/jittor/gcn_layer.py
- cogdl/operators/jt_spmm.py
- examples/jittor/gcn.py
- Add a gcn example written by Jittor
> [Feature] Jittor gcn example

- README.md
- README_CN.md
- cogdl/__init__.py
- docs/source/index.rst
> [Doc] Prepare v0.5.3 release

- docs/source/tutorial/custom_gnn.rst
- docs/source/tutorial/graph.rst
> Update doc tutorials

- .vscode/settings.json
- cogdl/models/emb/deepwalk.py
- cogdl/models/emb/dgk.py
- cogdl/models/emb/gatne.py
- cogdl/models/emb/metapath2vec.py
- cogdl/models/emb/node2vec.py
- docs/requirements.txt
- setup.py
- tests/models/emb/test_deepwalk.py
This request is referred to the issue #360 .
> update APIs for gensim 4.x

- cogdl/models/emb/complex.py
- cogdl/models/emb/distmult.py
- cogdl/models/emb/knowledge_base.py
- cogdl/models/emb/rotate.py
- cogdl/models/emb/transe.py
- cogdl/trainer/trainer_utils.py
> Small Changes

- cogdl/oag/oagbert_metainfo.py
Move tokenized tensors to the same device as model.
> [BugFix] Fix bugs in oagbert.encode_paper

- cogdl/datasets/__init__.py
- cogdl/datasets/stgat_data.py
- cogdl/datasets/stgcn_data.py
- cogdl/layers/__init__.py
- cogdl/layers/gat_layerii.py
- cogdl/layers/gcn_layerii.py
- cogdl/layers/stgat_layer.py
- cogdl/layers/stgcn_layer.py
- cogdl/models/__init__.py
- cogdl/models/nn/__init__.py
- cogdl/models/nn/stgat.py
- cogdl/models/nn/stgcn.py
- cogdl/utils/evaluator.py
- cogdl/wrappers/data_wrapper/__init__.py
- cogdl/wrappers/data_wrapper/traffic_prediction/__init__.py
- cogdl/wrappers/data_wrapper/traffic_prediction/stgat_dw.py
- cogdl/wrappers/data_wrapper/traffic_prediction/stgcn_dw.py
- cogdl/wrappers/default_match.py
- cogdl/wrappers/model_wrapper/__init__.py
- cogdl/wrappers/model_wrapper/traffic_prediction/__init__.py
- cogdl/wrappers/model_wrapper/traffic_prediction/stgat_mw.py
- cogdl/wrappers/model_wrapper/traffic_prediction/stgcn_mw.py
- docs/requirements.txt
- examples/simple_trafficPre/example.py
- tests/test_experiments.py
> Add stgcn code for traffic prediction task

- README.md
- README_CN.md
- cogdl/__init__.py
- docs/source/conf.py
- docs/source/index.rst
- examples/dgraph/README.md
> [Doc] Update v0.6

- cogdl/datasets/grb_data.py
Update download links of GRB data
> [Dataset] Update download links of GRB data
